### ISSUE TITLE
fail build

### ISSUE THREAD

**Issue by sl1pkn07** [abique/hefur#10]
fail build in b5b5a2 (mimosa 693580a)

http://sl1pkn07.wtf/paste/view/5b758f71

greetings

**Comment by abique** [comment]
Hi,

The master now builds, if you build from git, you have to update your local copy of mimosa:
git pull && git submodule update

I'll try to provide updated source archive.

Cheers,

**Comment by abique** [comment]
Thanks for the report by the way ;-)
