### ISSUE TITLE
Cannot download torrent from tracker page

### ISSUE THREAD

**Issue by glenntanner3** [abique/hefur#11]
Cannot download torrent file from tracker using :6969/file/file.torrent?info_hash=XXXXXX. 

Neat little simple tracker you have made, please keep developing it.

**Comment by abique** [comment]
Hey thank you man :D

I'll look into your issue.

I have an idea to improve it: make it serve a directory as http server, but also as torrent seed and auto create the the .torrent files :)

**Comment by glenntanner3** [comment]
I like it and don't let it bother or overwhelm you, but i'm going to post issues for improvement. But so far so good.

**Comment by glenntanner3** [comment]
This was also due to file permission issue #12
