### ISSUE TITLE
Add torrent to tracker using hefurctl does not create .torrent file in /var/lib/hefurd/

### ISSUE THREAD

**Issue by glenntanner3** [abique/hefur#12]
When adding a torrent hefurctl should internally copy the torrent from <src> to the <hefur config> folder.

**Comment by glenntanner3** [comment]
Likewise remove does not delete or give a switch to delete the .torrent file

**Comment by glenntanner3** [comment]
Although all the torrent files are globally readable, I encountered 3 issues because they were not did not have the same ownership as hefur. I think having hefur create it's own copy of the torrent file is going to be really important for the long term scope of your software.

**Comment by abique** [comment]
Hey, this is a good idea.
