### ISSUE TITLE
Can't "make" Ubuntu 12.04

### ISSUE THREAD

**Issue by MatheusGrilo** [abique/hefur#18]
1st make ~~> http://pastebin.com/vnKmRWKz

2nd make (error)

> In file included from /root/hefur/mimosa/mimosa/http/request-writer.cc:3:0:
> /root/hefur/mimosa/mimosa/http/message-writer.hxx: In instantiation of 'mimosa::http::MessageWriter<Channel, Message>::~MessageWriter() [with Channel = mimosa::http::ClientChannel; Message = mimosa::http::Request]':
> /root/hefur/mimosa/mimosa/http/request-writer.hh:18:57:   required from here
> /root/hefur/mimosa/mimosa/http/message-writer.hxx:28:9: error: ambiguous default type conversion from 'mimosa::RefCountedPtrmimosa::stream::Buffer'
> /root/hefur/mimosa/mimosa/http/message-writer.hxx:28:9: error:   candidate conversions include 'template<class U> mimosa::RefCountedPtr::operator mimosa::RefCountedPtr<U>() const [with U = U; T = mimosa::stream::Buffer]'
> /root/hefur/mimosa/mimosa/http/message-writer.hxx:28:9: error: type 'class mimosa::RefCountedPtrmimosa::stream::Buffer' argument given to 'delete', expected pointer
> make[2]: **\* [mimosa/mimosa/http/CMakeFiles/mimosa-http.dir/request-writer.cc.o] Error 1
> make[1]: **\* [mimosa/mimosa/http/CMakeFiles/mimosa-http.dir/all] Error 2
> make: **\* [all] Error 2

There are some errors (warnings) in 1st make, but they didn't stop the process.
# EDIT Using the latest mimosa version.

PS: I fixed the errors "nettle/sha1.h" 2 and 3 downloading the files and putting them into the nettle's folder.

**Comment by abique** [comment]
Hey,

I did update mimosa in Hefur, can you try to build again?

Thank you,
Alex.

**Comment by MatheusGrilo** [comment]
>[ 68%] Building CXX object mimosa/mimosa/http/CMakeFiles/mimosa-http.dir/request-writer.cc.o
In file included from /root/hefur/mimosa/mimosa/http/request-writer.cc:3:0:
/root/hefur/mimosa/mimosa/http/message-writer.hxx: In instantiation of 'mimosa::http::MessageWriter<Channel, Message>::~MessageWriter() [with Channel = mimosa::http::ClientChannel; Message = mimosa::http::Request]':
/root/hefur/mimosa/mimosa/http/request-writer.hh:18:57:   required from here
/root/hefur/mimosa/mimosa/http/message-writer.hxx:28:9: error: ambiguous default type conversion from 'mimosa::RefCountedPtr<mimosa::stream::Buffer>'
/root/hefur/mimosa/mimosa/http/message-writer.hxx:28:9: error:   candidate conversions include 'template<class U> mimosa::RefCountedPtr::operator mimosa::RefCountedPtr<U>() const [with U = U; T = mimosa::stream::Buffer]'
/root/hefur/mimosa/mimosa/http/message-writer.hxx:28:9: error: type 'class mimosa::RefCountedPtr<mimosa::stream::Buffer>' argument given to 'delete', expected pointer
make[2]: *** [mimosa/mimosa/http/CMakeFiles/mimosa-http.dir/request-writer.cc.o] Error 1
make[1]: *** [mimosa/mimosa/http/CMakeFiles/mimosa-http.dir/all] Error 2
>make: *** [all] Error 2

I guess the problem is here:
>> CC=gcc CXX=g++ cmake -DCMAKE_INSTALL_PREFIX=/usr ..
-- The C compiler identification is GNU
-- The CXX compiler identification is GNU
-- Check for working C compiler: /usr/bin/gcc
-- Check for working C compiler: /usr/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/g++
-- Check for working CXX compiler: /usr/bin/g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- checking for module 'gnutls'
--   found gnutls, version 2.12.14
-- Found GnuTLS: /usr/lib/x86_64-linux-gnu/libgnutls.so
hefur version: 0.4
control interface: ON
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.3.4")
-- Looking for strchrnul
-- Looking for strchrnul - found
-- Looking for timegm
-- Looking for timegm - found
-- Looking for sched_setaffinity
-- Looking for sched_setaffinity - found
-- Configuring done
-- Generating done
>-- Build files have been written to: /root/hefur/build
