### ISSUE TITLE
add support for BitTorrent v2

### ISSUE THREAD

**Issue by pabs3** [abique/hefur#31]
BitTorrent v2 (which switches from SHA-1 to SHA-256) is gaining steam and [is now supported](https://blog.libtorrent.org/2020/09/bittorrent-v2/) by libtorrent and BiglyBT (Vuze/Azureus) continuation. 

It would be great to have support for BitTorrent v2 in Hefur, since [Debian uses Hefur](http://bttracker.debian.org:6969/stat) and we are likely to want to use BitTorrent v2 as soon as possible.

**Comment by abique** [comment]
Hi,
I will look into it this week.
Regards,
Alex

**Comment by abique** [comment]
I've had a quick look and believe we could get something working by the end of the week.

**Comment by pabs3** [comment]
Awesome! I wasn't expecting such a quick response :)

-- 
bye,
pabs

https://bonedaddy.net/pabs3/

**Comment by abique** [comment]
I think it is now implemented.
I will start testing it, you can start testing it too :)

**Comment by abique** [comment]
It is not ready yet. Wait some more.

**Comment by abique** [comment]
I think it is good for testing.

Please fill issues you find into new tickets.

Many thanks,
Alex

**Comment by abique** [comment]
Version 1.0 released.

**Comment by abique** [comment]
@pabs3 How's going debian switch to BitTorrent v2?

**Comment by pabs3** [comment]
Looks like the folks we outsource our torrent tracker to are still
using Hefur 0.4. I've pinged them about the status of upgrading it.

http://bttracker.debian.org:6969/stat

In addition the .torrent file generator we are using doesn't support
BitTorrent v2 yet and is fairly unmaintained, so it won't yet be
possible for Debian torrents to have BitTorrent v2 hashes in them. 

-- 
bye,
pabs

https://bonedaddy.net/pabs3/
