### ISSUE TITLE
Symbolic links in whitelist directory are ignored

### ISSUE THREAD

**Issue by nielsAD** [abique/hefur#35]
While recursively iterating the torrent directory, symbolic links to directories are skipped.

I guess we would have to handle `S_ISLNK` in [mimosa/fs/find.cc](https://github.com/abique/mimosa/blob/375064d46287fb7ed6886c48dd91c9e03e2d0633/mimosa/fs/find.cc#L34).

**Comment by abique** [comment]
I've checked quickly the code I did not see something preventing symbolic links.
I'll run some tests later.

**Comment by abique** [comment]
This commit adds some test data for your issue: https://github.com/abique/hefur/commit/bc8d11af3e94693873fbaf23a3ca29e8af6876c1
But then everything works fine.
Please can you double check your issue? Many thanks :)

**Comment by nielsAD** [comment]
You're right, this was a permission issue on my end. Thanks!
